
name: Pull Request Validation

on:
  pull_request:
    branches: [ main, master ]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Validate PR requirements
      run: |
        echo "Validating Pull Request requirements..."
        
        # Check for proper PR structure
        echo "✅ PR validation started"
        
        # Basic file structure validation
        required_files=("index.html" "bazi.html" "report.html" "README.md")
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ Required file exists: $file"
          else
            echo "❌ Missing required file: $file"
            exit 1
          fi
        done
        
        # JavaScript syntax validation
        echo "Checking JavaScript syntax..."
        for file in js/*.js; do
          if [ -f "$file" ]; then
            if node -c "$file"; then
              echo "✅ $file syntax is valid"
            else
              echo "❌ $file has syntax errors"
              exit 1
            fi
          fi
        done
        
        # JSON validation
        echo "Checking JSON files..."
        for file in $(find . -name "*.json" -not -path "./node_modules/*"); do
          if [ -f "$file" ]; then
            if python3 -m json.tool "$file" > /dev/null; then
              echo "✅ $file is valid JSON"
            else
              echo "❌ $file has JSON syntax errors"
              exit 1
            fi
          fi
        done
        
        echo "✅ PR validation completed successfully"
